# Generated by Django 4.1.3 on 2022-12-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='Para',
            field=models.EmailField(default=999, max_length=254),
            preserve_default=False,
        ),
    ]
